### ISSUE TITLE
[ethers-ext] sendTransactionAsFeePayer returns null sometimes

### ISSUE THREAD

**Issue by kjeom** [klaytn/web3klaytn#499]
Even though the transaction success, it returns null, not transaction hash.

**Comment by nohkwak** [comment]
@blukat29 @kjeom 

I think this is because we return not txHash but getTransaction(). 

      const **txhash** = await this.provider.send("klay_sendRawTransaction", [signedTx]);
      return await this.provider**.getTransaction(txhash)**;
      
How about changing like below? 

      return await this.provider.send("klay_sendRawTransaction", [signedTx]);

**Comment by blukat29** [comment]
@nohkwak Obviously that changes the return type. You cannot do that.

We need to replicate the polling behavior as in [JsonRpcProvider.sendTransaction](https://github.com/ethers-io/ethers.js/blob/v5.7.2/packages/providers/src.ts/json-rpc-provider.ts#L283).

**Comment by nohkwak** [comment]
Thanks. 
The code below is similar to original context.
and it is working. 

      const txhash = await this.provider.send("klay_sendRawTransaction", [signedTx]);
      let ttx : TransactionResponse = <TransactionResponse> ptx;
      ttx.hash = txhash;
      return await this.provider._wrapTransaction(ttx, txhash);

**Comment by blukat29** [comment]
@nohkwak That should be a workaround. Just check that wrapTransaction(ptx) is identical to provider.getTransaction(txhash) with respect to every field.

**Comment by blukat29** [comment]
@nohkwak I see that most fields are intact. I'm okay with using your workaround. Let's switch to the poll mechanism later.

**Comment by nohkwak** [comment]
@blukat29  Then, How do you think about Pull Requesting of the workaround code above?

**Comment by blukat29** [comment]
I absolutely prefer the poll method.

**Comment by kjeom** [comment]
@nohkwak Could you comment the PR numbers to resolve this issue?

**Comment by nohkwak** [comment]
The above issue was only discussed and no PR was made.
How about discussing this issue at the meeting tomorrow morning and resolving with the new PR?
