### ISSUE TITLE
[ethers-ext] seems to be complex when sending a transaction with multisig

### ISSUE THREAD

**Issue by kjeom** [klaytn/web3klaytn#500]
When we sign a transaction with multisig, it looks like redundant. I think we can make it without decoding the transaction.

```javascript
  // sign 1
  const wallet = new Wallet(senderAddr, senderNewPriv1, provider);
  let ptx = await wallet.populateTransaction(tx);
  const txHashRLP = await wallet.signTransaction(ptx);
  console.log("TxHashRLP", txHashRLP);

  // sign 2
  const wallet2 = new Wallet(senderAddr, senderNewPriv2, provider);
  let decodedTx = wallet2.decodeTxFromRLP(txHashRLP);
  console.log(decodedTx);
  let ptx2 = await wallet2.populateTransaction(decodedTx);
  const txHashRLP2 = await wallet2.signTransaction(ptx2);
  console.log("TxHashRLP2", txHashRLP2);

  // sign 3
  const wallet3 = new Wallet(senderAddr, senderNewPriv3, provider);
  let decodedTx2 = wallet3.decodeTxFromRLP(txHashRLP2);
  console.log(decodedTx2);
  let ptx3 = await wallet3.populateTransaction(decodedTx2);
  const txHashRLP3 = await wallet3.signTransaction(ptx3);
  console.log("TxHashRLP3", txHashRLP3);
```

**Comment by nohkwak** [comment]
Would it be okay if the developer does not necessarily need to run decodeTxFromRLP as shown below, 
but use just the population function and signTransaction function?

  // sign 1
  const wallet = new Wallet(senderAddr, senderNewPriv1, provider);
  let ptx = await wallet.populateTransaction(tx);
  const txHashRLP = await wallet.signTransaction(ptx);
  console.log("TxHashRLP", txHashRLP);

  // sign 2
  const wallet2 = new Wallet(senderAddr, senderNewPriv2, provider);
  let ptx2 = await wallet2.populateTransaction(txHashRLP);
  const txHashRLP2 = await wallet2.signTransaction(ptx2);
  console.log("TxHashRLP2", txHashRLP2);

  // sign 3
  const wallet3 = new Wallet(senderAddr, senderNewPriv3, provider);
  let ptx3 = await wallet3.populateTransaction(txHashRLP2);
  const txHashRLP3 = await wallet3.signTransaction(ptx3);
  console.log("TxHashRLP3", txHashRLP3);

**Comment by kjeom** [comment]
Furthermore the last person who sign the transaction cannot use just the `sendTransaction` method.

**Comment by nohkwak** [comment]
https://github.com/klaytn/web3klaytn/pull/501
