### ISSUE TITLE
Reflect API changes from Kaia v1.0.0

### ISSUE THREAD

**Issue by blukat29** [klaytn/web3klaytn#619]
1. https://github.com/klaytn/klaytn/pull/2111
  - NEW klay_getBlsInfos
  - NEW klay_getActiveAddressFromRegistry
  - NEW klay_getAllRecordsFromRegistry
2. https://github.com/klaytn/klaytn/pull/2148
    https://github.com/klaytn/klaytn/pull/2178
  - NEW klay_getTotalSupply
3. https://github.com/klaytn/klaytn/pull/2116
  - FIX klay_gasPrice
  - FIX klay_maxPriorityFeePerGas
  - FIX klay_feeHistory
4. Outdated debug_trece API docs
  - The "TracingOptions" model used in `debug_trace*` APIs

**Comment by blukat29** [comment]
1. Add query APIs for KIP113, KIP149

- **klay_getBlsInfos**: See https://kips.klaytn.foundation/KIPs/kip-113 for the API spec and example
- **klay_getActiveAddressFromRegistry** and **klay_getAllRecordsFromRegistry**: See https://kips.klaytn.foundation/KIPs/kip-149 for the API spec and example

**Comment by blukat29** [comment]
2. Add klay_getTotalSupply API: TBU

- **klay_getTotalSupply**
  - Returns the native token token supply by tracking block rewards and various burning mechanisms. If some components are not available then a partial result is returned.
  - Params
    - block number or block hash
  - Returns
    - number: The last block number the token supply is accumulated to.
    - totalMinted: Accumulated block rewards minted up to number plus the genesis total supply.
    - burntFee: Accumulated transaction fees burnt.
    - zeroBurn: The balance of the address 0x0, which is a canonical burn address. It is `null` if the state at the requested block is not available.
    - deadBurn: The balance of the address 0xdead, which is another canonical burn address. It is `null` if the state at the requested block is not available.
    - kip103Burn: The amounts burnt by KIP-103 TreasuryRebalance, if executed. It is `null` if KIP-103 is configured and the hardfork block passed but memo field is not set in the contract. It is 0 if KIP-103 is not configured or the hardfork block is larger than the requested block.
    - kip160Burn: The amounts burnt by KIP-160 TreasuryRebalanceV2, if executed. It is `null` if KIP-160 is configured and the hardfork block passed but memo field is not set in the contract. It is 0 if KIP-160 is not configured or the hardfork block is larger than the requested block.
    - totalBurnt: Sum of the burns from above reasons. It is `null` if some components cannot be determined.
    - totalSupply: The calculated total supply of the native token at the given block. Difference between totalMinted and totalBurnt. It is `null` if some components cannot be determined.
    - (optional) error: The reasons why some components cannot be determined.
  - Example
	```js
	> klay.getTotalSupply("latest")
	{
	   burntFee: "0x29ec817ffd11a9cd3a4b3",
	   deadBurn: "0x40c166a428511ad626d306",
	   kip103Burn: "0x111d0449fb2a238eca3b1720",
	   kip160Burn: "0x0",
	   number: "0x93295ce",
	   totalBurnt: "0x11606478b75245c43d358ed9",
	   totalMinted: "0x249a79581de10f4cd3000000",
	   totalSupply: "0x133a14df668ec98895ca7127",
	   zeroBurn: "0x0"
	}
	```

**Comment by blukat29** [comment]
3. Priority fee related RPCs

Requests for docs
- Categorize `klay_gasPrice, klay_gasPriceAt, eth_gasPrice` under [Gas] not [Configuration]
- Change the description of klay_gasPrice, eth_gasPrice:
  - description: Returns a suggested gasPrice or maxFeePerGas. The suggested price depends on the hardfork status.
      - Fixed unit price before Magma
      - Twice the base fee before Kaia
      - Base fee plus suggested priority fee after Kaia
  - result: Suggested price in kei
- Change the description of klay_maxPriorityFeePerGas, eth_maxPriorityFeePerGas
  - description: Returns a suggested gasPrice or maxPriorityFeePerGas. The suggested price depends on the hardfork status.
    - Fixed unit price before Magma
    - Zero before Kaia
    - Suggested priority fee from fee history, after Kaia
  - result: Suggested price in kei
- Change the description of klay_feeHistory, eth_feeHistory
  - params and result: Use https://github.com/klaytn/kips/blob/main/KIPs/kip-162.md

**Comment by blukat29** [comment]
4. Outdated debug_trece API docs

For example in https://docs.klaytn.foundation/docs/references/json-rpc/debug/trace-transaction/,

**[Request > params > TracingOptions]**

- **disableStorage** boolean
    Setting this to true will disable storage capture in the null (structLog) tracer (default: false).
- **disableMemory** boolean
    Setting this to true will disable memory capture in the null (structLog) tracer (default: false).
- **disableStack** boolean
    Setting this to true will disable stack capture in the null (structLog) tracer (default: false).
- **timeout** string
    Overrides the default timeout of 5 seconds for trace-enabled EVM execution. A duration string can be anything that is accepted by [Go time.ParseDuration](https://pkg.go.dev/time#ParseDuration) function such as "10s" or "300ms".
- **loggerTimeout** string
    Overrides the default timeout of 1 second for exporting the trace result to JSON. Logger timeout prevents the resource exhaustion induced by encoding a huge trace into JSON. A duration string can be anything that is accepted by [Go time.ParseDuration](https://pkg.go.dev/time#ParseDuration) function such as "10s" or "300ms".
- **tracer** string
    Possible values: [null, 4byteTracer, callTracer, fastCallTracer, evmdisTracer, noopTracer, opcountTracer, prestateTracer, revertTracer, unigramTracer, bigramTracer, trigramTracer, custom javascript tracer code]
    (1) If this field is empty or null, then the structLog tracer is used where the execution of every opcode is shown in detail. This null tracer is extremely heavy and usually too verbose for any debugging purpose, so it is advised to use other predefined tracers.
    (2) This field can be the name of one of the predefined tracers shown below.
    - 4byteTracer: traces 4-byte solidity function signatures.
    - callTracer: a slow version of fastCallTracer. It is deprecated in favor of fastCallTracer.
    - fastCallTracer: traces internal contract calls, gas usage, and call results.
    - evmdisTracer: returns information needed to perform evmdis-style disassembly.
    - noopTracer: is a template tracer that does nothing.
    - opcountTracer: is a sample tracer that counts the executed opcode.
    - prestateTracer: returns information needed to construct a custom local genesis state that this transaction can run on.
    - revertTracer: returns the revert reason, or an empty string if the transaction has not reverted.
    - unigramTracer: counts the occurrence of each opcode.
    - bigramTracer: counts the occurrence of two consecutive opcodes.
    - trigramTracer: counts the occurrence of three consecutive opcodes.

  (3) otherwise this field is interpreted as a piece of javascript code. You can find more about custom JS tracer [here](https://docs.chainstack.com/reference/custom-js-tracing-ethereum) and [here](https://geth.ethereum.org/docs/developers/evm-tracing/custom-tracer). Below is an example custom tracer that prints the gasUsed after each opcode `"{gasUsed: [], step: function(log) { this.gasUsed.push(log.getGas()); }, result: function() { return this.gasUsed; }, fault: function() {}}"`. Note that some nodes with `--rpc.unsafe-debug.disable` option will prohibit custom tracer.


**[Responses > result]**

- **result** object
  The result depends on the tracer type.

**Comment by kjeom** [comment]
- #625 
- #624
